theme: jekyll-theme-minimal









title: Durga Chintalapudi
author: Durga Chintalapudi
description: Bookmark this to keep an eye on my project updates!

# If you publish as a project page (not username.github.io) set `baseurl: "/repo-name"`
# baseurl: ""
